### ISSUE TITLE
THETA parameter gets put in RUV panel rather than requested IIV panel

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/pmparams#25]
This entry ends up in the RUV section. I think the issue is in `pmparams:::getPanelName` ... the case_when logic doesn't cover this case and it gets set to `NA`; that's how it ends up in RUV. 

```yaml
THETA7: 
  abb: "BC for IIV-CL/F" 
  desc: "Box-Cox transformation factor"
  panel: IIV 
  trans: none 
```
